version: '3.1'
services:
  cifra-service:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - cifra-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cifra-db:5432/cifra
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password

  cifra-db:
    image: postgres:13.7-alpine
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cifra
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password